apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: httpd1-service
  labels:
    app.kubernetes.io/name: httpd
    app.kubernetes.io/part-of: httpd
spec:
  ports:
    - port: 8000
      name: httpd
  selector:
    app: httpd1
  clusterIP: None
